* autopep8.el

[[https://travis-ci.org/paetzke/py-autopep8.el][https://travis-ci.org/wizmer/autopep8-mode.svg?branch=master]]
# [[http://melpa.org/#/py-autopep8][http://melpa.org/packages/autopep8-badge.svg]]

Minor mode that autopep8 current buffer before each save with, which use the external
=autopep8= tool to tidy up the current buffer according to Python's PEP8.

To install =autopep8= and =autopep8=:

#+BEGIN_SRC bash
$ pip install autopep8
$ wget https://raw.githubusercontent.com/wizmer/autopep8-mode/master/autopep8.el \
        -O /your/path/autopep8.el
#+END_SRC

Add the before-save-hook to your =~/.emacs=:

#+BEGIN_SRC lisp
(require 'autopep8-mode)
(add-hook 'python-mode-hook 'autopep8-mode)
#+END_SRC

You can install =autopep8= also with [[https://github.com/milkypostman/melpa][MELPA]]:

#+BEGIN_SRC lisp
M-x package-install RET
autopep8 RET
#+END_SRC

Now every time you save your Python file autopep8 will be executed on the current buffer.

To customize the behaviour of =autopep8= you can set the =autopep8-options= e.g.

#+BEGIN_SRC lisp
(setq autopep8-options '("--max-line-length=100"))
#+END_SRC

The autopep8 program path can be customized as well:
#+BEGIN_SRC lisp
(setq autopep8-command '"/foo/bar/my/autopep8")
#+END_SRC


** Functions

=M-x autopep8-buffer=: Uses the =autopep8= tool to reformat the current buffer.


** Bugs and improvements

Feel free to open tickets or send pull requests with improvements.
These [[https://github.com/paetzke/py-autopep8.el/graphs/contributors][contributors]] have done so.


** Thanks
Thanks to Friedrich Paetzke for writing the original package.
